<?php
/**
 * @file
 * Code for the Ntxuva Admin feature.
 */

include_once 'ntxuva_admin.features.inc';

/**
 * Implements hook_page_build().
 */
function ntxuva_admin_page_build(&$page) {
  global $custom_theme, $theme, $user;

  if (!empty($user->theme)) {
    $current_theme = $user->theme;
  }
  elseif (!empty($custom_theme)) {
    $current_theme = $custom_theme;
  }
  else {
    $current_theme = $theme ? $theme : variable_get('theme_default', 'garland');
  }
  if ($current_theme == "ember"){
    drupal_add_css(drupal_get_path('module', 'ntxuva_admin') . '/css/mopa-admin-style.css', array('weight' => 9999));
    drupal_add_css(
      'img {max-width: none;}',
      array(
        'group' => CSS_THEME,
        'type' => 'inline',
      )
    );
  }
  if (in_array('edit', arg())) {
    drupal_add_js(drupal_get_path('module', 'ntxuva_admin') . '/ntxuva_admin.js', array('scope' => 'footer', 'weight' => 5));
  }
}
